---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: backendvm
spec:
  redirect:
    service: backendvm
    datacenter: linux

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: rootk8s
spec:
  meshGateway: 
    mode: local

---
apiVersion: v1
kind: Service
metadata:
  name: rootk8s
spec:
  selector:
    app: rootk8s
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090

---
# Backend for DC2 Root
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rootk8s
  labels:
    app: rootk8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rootk8s
  template:
    metadata:
      labels:
        app: rootk8s
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "backendvm:9091"
    spec:
      containers:
      - name: rootk8s
        image: nicholasjackson/fake-service:v0.22.7
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "0.0.0.0:9090"
        - name: "UPSTREAM_URIS"
          value: "http://localhost:9091"
        - name: "NAME"
          value: "rootk8s"
        - name: "MESSAGE"
          value: "Hello World"