# Available parameters and their default values for the Consul chart.
# Server, when enabled, configures a server cluster to run. This should
# be disabled if you plan on connecting to a Consul cluster external to
# the Kube cluster.
global:
  # image: hashicorpdev/consul
  # imageK8S: hashicorpdev/consul-k8s:crd-controller-base-latest
  name: consul
server:
  replicas: 1
  bootstrapExpect: 1
  acls:
    manageSystemACLs: false


controller:
  enabled: true
ui:
  enabled: true
connectInject:
  enabled: true
  default: false  # true will inject by default, otherwise requires annotation

  # Requires Consul v1.5+ and consul-k8s v0.8.1+
  centralConfig:
    enabled: "true"

    # defaultProtocol allows you to specify a convenience default protocol if
    # most of your services are of the same protocol type. The individual annotation
    # on any given pod will override this value. A protocol must be provided,
    # either through this setting or individual annotation, for a service to be
    # registered correctly. Valid values are "http", "http2", "grpc" and "tcp".
    defaultProtocol: "http"

