---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ProxyDefaults
metadata:
  name: global
spec:
  meshGateway:
    mode: local

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: payments
spec:
  upstreamConfig:
    defaults:
      meshGateway:
        mode: local

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: web
spec:
  upstreamConfig:
    defaults:
      meshGateway:
        mode: local

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: currency
spec:
  upstreamConfig:
    defaults:
      meshGateway:
        mode: local

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
spec:
  destination:
    name: payments
  sources:
    - name: web
      action: allow

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: currency
spec:
  destination:
    name: currency
  sources:
    - name: payments
      action: allow

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: payments
spec:
  redirect:
    datacenter: kubernetes

---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceResolver
metadata:
  name: currency
spec:
  redirect:
    datacenter: vms

---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    app: payments
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "currency:9091"
        "consul.hashicorp.com/transparent-proxy": "false"
    spec:
      serviceAccountName: payments
      containers:
      - name: payments
        image: nicholasjackson/fake-service:v0.22.7
        ports:
        - containerPort: 9090
        env:
        - name: "LISTEN_ADDR"
          value: "127.0.0.1:9090"
        - name: "NAME"
          value: "payments"
        - name: "MESSAGE"
          value: "Hello World"
        - name: "UPSTREAM_URIS"
          value: "http://localhost:9091"
