global:
  name: "consul"

  tls:
    enabled: true

  acls:
    manageSystemACLs: true
    createReplicationToken: true

  gossipEncryption:
    secretName: consul-gossip-encryption-key
    secretKey: key

  federation:
    enabled: true

server:
  replicas: 1
  bootstrapExpect: 1 # Should <= replicas count
  storage: 64Mi
  storageClass: local-path

client:
  enabled: true
  grpc: true

ui:
  enabled: true
  
  service:
    enabled: true

connectInject:
  enabled: true
  default: false  # true will inject by default, otherwise requires annotation

  centralConfig:
    enabled: "true"
    defaultProtocol: "tcp"
    proxyDefaults: |
      {
        "envoy_prometheus_bind_addr": "0.0.0.0:9102",
         "envoy_extra_static_clusters_json": "{\"connect_timeout\": \"3.000s\", \"dns_lookup_family\": \"V4_ONLY\", \"lb_policy\": \"ROUND_ROBIN\", \"load_assignment\": { \"cluster_name\": \"jaeger_9411\", \"endpoints\": [ { \"lb_endpoints\": [ {\"endpoint\": { \"address\": { \"socket_address\": { \"address\": \"jaeger-collector\", \"port_value\": 9411, \"protocol\": \"TCP\" } } } } ] } ] }, \"name\": \"jaeger_9411\", \"type\": \"STRICT_DNS\" }",
         "envoy_tracing_json": "{ \"http\": { \"config\": { \"collector_cluster\": \"jaeger_9411\", \"collector_endpoint\": \"/api/v1/spans\" }, \"name\": \"envoy.zipkin\" } }"
      }

meshGateway:
  enabled: true
  globalMode: local

  replicas: 1

  wanAddress:
    source: "Static"
    port: 443

  service:
    enabled: true
    type: LoadBalancer
    port: 443