---
apiVersion: v1
kind: Service
metadata:
  name: metrics
  labels:
    app: metrics
spec:
  selector:
    metrics: 'true'
  ports:
    - name: metrics
      protocol: TCP
      port: 9102
      targetPort: 9102

---
apiVersion: v1
kind: Service
metadata:
  name: public
spec:
  selector:
    app: api
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api_v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        metrics: 'true'
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/connect-service-upstreams: 'payments:9091'
    spec:
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.21.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: "NAME"
              value: "API"
            - name: "LISTEN_ADDR"
              value: "0.0.0.0:9090"
            - name: "UPSTREAM_URIS"
              value: "http://localhost:9091"
            - name: "TIMING_50_PERCENTILE"
              value: "10ms"
            - name: "TIMING_50_PERCENTILE"
              value: "10ms"
            - name: "TRACING_ZIPKIN"
              value: "http://tempo:9411"
