---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  selector:
    group: payments
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-v1-deployment
  labels:
    app: payments_v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments_v1
  template:
    metadata:
      labels:
        app: payments_v1
        group: payments
        metrics: enabled
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/service-meta-version: v1
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: nicholasjackson/fake-service:v0.22.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: "NAME"
              value: "PAYMENTS V1"
            - name: "LISTEN_ADDR"
              value: "127.0.0.1:9090"
            - name: "TIMING_50_PERCENTILE"
              value: "10ms"
            - name: "TRACING_ZIPKIN"
              value: "http://tempo:9411"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-v2-deployment
  labels:
    app: payments_v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments_v2
  template:
    metadata:
      labels:
        app: payments_v2
        group: payments
        metrics: enabled
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/service-meta-version: v2
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: nicholasjackson/fake-service:v0.21.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: "NAME"
              value: "PAYMENTS V2"
            - name: "LISTEN_ADDR"
              value: "127.0.0.1:9090"
            - name: "TIMING_50_PERCENTILE"
              value: "10ms"
            - name: "TRACING_ZIPKIN"
              value: "http://tempo:9411"
