apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: applications
  namespace: #{{ .Vars.monitoring_namespace }}
  labels:
    app: applications
    release: prometheus
spec:
  selector:
    matchLabels:
      app: metrics
  jobLabel: applications
  endpoints:
  - port: metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: applications
  namespace: #{{ .Vars.monitoring_namespace }}
  labels:
    app: applications
    release: prometheus
spec:
  selector:
    matchLabels:
      metrics: enabled
  podMetricsEndpoints:
  - port: "9102"
