---

name: Test Blueprints
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    name: Test Blueprints
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [
          'consul-docker/',
          'consul-ingress/',
          'docs',
          'vault-k8s/',
          'vault-dev/'
        ]

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 3

      - name: Check for changes
        id: check_for_changes
        run: |
          echo "::set-output name=change_count::$(git diff --name-only  HEAD^ HEAD | grep '${{ matrix.folder }}' | wc -l)"

      - name: Get dependencies
        if: ( steps.check_for_changes.outputs.change_count != '0' || github.event_name == 'schedule' )
        run: |
          echo "changes: ${{ steps.check_for_changes.outputs.change_count }} event: ${{ github.event_name }}"
          curl https://shipyard.run/install | bash

      - name: Run tests - ${{ matrix.blueprint }}
        if: ( steps.check_for_changes.outputs.change_count != '0' || github.event_name == 'schedule' )
        run: |
          shipyard test ${{ matrix.folder }}

      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          tile: ${{ matrix.folder }}
          description: "Functional tests for ${{ matrix.folder }}"
